### ISSUE TITLE
terminal starts on mode switch

### ISSUE THREAD

**Issue by patrik-csak** [patrik-csak/auto-terminal-profile#2]
if terminal isn't running, then the appearance mode switches, terminal opens

it would be a better experience if this didn't happen

**Comment by debashis1992** [comment]
Is this change taken into consideration? I'm facing the same issue. Would be really glad if this gets addressed. 
Thanks. Great Job!!!

**Comment by patrik-csak** [comment]
fixed in 96405a5e, which is published in v3.0.2

**Comment by patrik-csak** [comment]
fixed in 96405a5e, which is published in v3.0.2
